version = 0.1

[default.deploy.parameters]
stack_name = "notify-contributions"
resolve_s3 = true
s3_prefix = "notify-contributions"
region = "ap-northeast-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
